# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Jacoco report artifact
      uses: actions/upload-artifact@v1
      with:
        name: jacoco-report
        path: target/site/jacoco/jacoco.xml
  report:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup codacy coverage
      run: |
        curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
        chmod +x codacy-coverage-reporter
    - name: Download Jacoco report artifact
      uses: actions/download-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: target/site/jacoco
    - name: Send coverage report
      env:
        CODACY_PROJECT_TOKEN : ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        ./codacy-coverage-reporter report -l Java 


